package com.bibler.awesome.bibness.assembler.tests;

import java.io.File;
import java.util.ArrayList;

import com.bibler.awesome.bibnes.assembler.Assembler;
import com.bibler.awesome.bibnes.assembler.InstructionLine;
import com.bibler.awesome.bibnes.assembler.Label;
import com.bibler.awesome.bibnes.io.TextReader;
import com.bibler.awesome.bibnes.systems.Memory;
import com.bibler.awesome.bibnes.utils.AssemblyUtils;
import com.bibler.awesome.bibnes.utils.StringUtils;

import junit.framework.TestCase;

public class ParseTest extends TestCase {
	
	public void testInstructionParse() {
		Assembler assembler = new Assembler();
		String s = "ADC #$F2";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "AND";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "ASL";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BCC";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BCS";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BEQ";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BIT";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BMI";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BNE";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BPL";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BRK";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BVC";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BVS";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "CLC";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "CLD";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "CLI";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "CLV";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "CMP";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "CPX";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "CPY";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "DEC";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "DEX";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "DEY";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "EOR";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "INC";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "INX";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "INY";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "JMP";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "JSR";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "LDA";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "LDX";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "LDY";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "LSR";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "ORA";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "PHA";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "PHP";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "PLA";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "PLP";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "ROL";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "ROR";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "RTI";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "RTS";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "SBC";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "SEC";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "SED";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "SEI";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "STA";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "STX";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "STY";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "TAX";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "TAY";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "TSX";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "TXA";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "TXS";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "TYA";
		assertTrue(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		//Check some fake op codes
		s = "ANR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "BNR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "CNR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "DNR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "ENR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "INR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "JNR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "LNR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "ONR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "PNR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "RNR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "SNR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		s = "TNR";
		assertFalse(assembler.matchOpCode(StringUtils.trimWhiteSpace(s)));
		
	}
	
	public void testOpCodeParseAccumulator() {
		Assembler assembler = new Assembler();
		String s = "  ASL A";
		assembler.parseOpCode(s);
		assertEquals(0x0A, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  LSR A";
		assembler.parseOpCode(s);
		assertEquals(0x4A, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  ROL A";
		assembler.parseOpCode(s);
		assertEquals(0x2A, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  ROR A";
		assembler.parseOpCode(s);
		assertEquals(0x6A, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		
	}
	
	public void testOpCodeParseImplied() {
		Assembler assembler = new Assembler();
		String s = "  BRK";
		assembler.parseOpCode(s);
		assertEquals(0x00, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  CLC";
		assembler.parseOpCode(s);
		assertEquals(0x18, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  SEC";
		assembler.parseOpCode(s);
		assertEquals(0x38, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  CLI";
		assembler.parseOpCode(s);
		assertEquals(0x58, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  SEI";
		assembler.parseOpCode(s);
		assertEquals(0x78, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  CLV";
		assembler.parseOpCode(s);
		assertEquals(0xB8, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  CLD";
		assembler.parseOpCode(s);
		assertEquals(0xD8, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  SED";
		assembler.parseOpCode(s);
		assertEquals(0xF8, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  NOP";
		assembler.parseOpCode(s);
		assertEquals(0xEA, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  TAX";
		assembler.parseOpCode(s);
		assertEquals(0xAA, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  TXA";
		assembler.parseOpCode(s);
		assertEquals(0x8A, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  DEX";
		assembler.parseOpCode(s);
		assertEquals(0xCA, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  INX";
		assembler.parseOpCode(s);
		assertEquals(0xE8, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  TAY";
		assembler.parseOpCode(s);
		assertEquals(0xA8, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  TYA";
		assembler.parseOpCode(s);
		assertEquals(0x98, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  DEY";
		assembler.parseOpCode(s);
		assertEquals(0x88, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  INY";
		assembler.parseOpCode(s);
		assertEquals(0xC8, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  RTI";
		assembler.parseOpCode(s);
		assertEquals(0x40, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  RTS";
		assembler.parseOpCode(s);
		assertEquals(0x60, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  TXS";
		assembler.parseOpCode(s);
		assertEquals(0x9A, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  TSX";
		assembler.parseOpCode(s);
		assertEquals(0xBA, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  PHA";
		assembler.parseOpCode(s);
		assertEquals(0x48, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  PLA";
		assembler.parseOpCode(s);
		assertEquals(0x68, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  PHP";
		assembler.parseOpCode(s);
		assertEquals(0x08, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		s = "  PLP";
		assembler.parseOpCode(s);
		assertEquals(0x28, assembler.getOpCode());
		assertEquals(0, assembler.getAddress());
		
	}
	
	public void testOpCodeParseZeroPage() {
		Assembler assembler = new Assembler();
		String s = "  ASL $45";
		assembler.parseOpCode(s);
		assertEquals(0x06, assembler.getOpCode());
		assertEquals(0x45, assembler.getAddress());
		s = "  LSR $F2";
		assembler.parseOpCode(s);
		assertEquals(0x46, assembler.getOpCode());
		assertEquals(0xF2, assembler.getAddress());
		s = "  LSR $F2,X";
		assembler.parseOpCode(s);
		assertEquals(0x56, assembler.getOpCode());
		assertEquals(0xF2, assembler.getAddress());
		s = "  ROL 32";
		assembler.parseOpCode(s);
		assertEquals(0x26, assembler.getOpCode());
		assertEquals(32, assembler.getAddress());
		s = "  ROR $ED";
		assembler.parseOpCode(s);
		assertEquals(0x66, assembler.getOpCode());
		assertEquals(0xED, assembler.getAddress());
	}
	
	public void testOpCodeParseAbsolute() {
		Assembler assembler = new Assembler();
		String s = "  ASL $4400";
		assembler.parseOpCode(s);
		assertEquals(0x0E, assembler.getOpCode());
		assertEquals(0x4400, assembler.getAddress());
		s = "  LSR $4200";
		assembler.parseOpCode(s);
		assertEquals(0x4E, assembler.getOpCode());
		assertEquals(0x4200, assembler.getAddress());
		s = "  LSR $4400,X";
		assembler.parseOpCode(s);
		assertEquals(0x5E, assembler.getOpCode());
		assertEquals(0x4400, assembler.getAddress());
		s = "  ROL 17408";
		assembler.parseOpCode(s);
		assertEquals(0x2E, assembler.getOpCode());
		assertEquals(0x4400, assembler.getAddress());
		s = "  ROR $4400";
		assembler.parseOpCode(s);
		assertEquals(0x6E, assembler.getOpCode());
		assertEquals(0x4400, assembler.getAddress());
		
	}
	
	public void testFromFile() {
		Assembler assembler = new Assembler();
		Memory machineCode = assembler.passOne(AssemblyUtils.processFile(new File("C:/users/ryan/desktop/test.asm")));
		assembler.writeMachineCodeToFile(new File("C:/users/ryan/desktop/textTest.bin"), machineCode);
		assembler.printPassTwoLines();
	}
	
	

}
